const {defineSecret} = require("firebase-functions/params");
const {GoogleGenAI} = require("@google/genai");
const {onRequest} = require("firebase-functions/https");
const {OpenAI} = require("openai");
const admin = require("firebase-admin");
const { FieldValue } = require("firebase-admin/firestore");

const GEMINI_API_KEY = defineSecret("GEMINI_API_KEY");
const DEEPSEEK_API_KEY = defineSecret("DEEPSEEK_API_KEY");

const {constellationApi} = require("./constellationApi.js");

if (admin.apps.length === 0) {
  admin.initializeApp();
}
const db = admin.firestore();

exports.constellationApi = constellationApi;

const SYSTEM_PROMPT = `
You are Morgan, an advanced AI Knowledge Mapping Assistant. Your primary job is to answer user questions while simultaneously monitoring the conversation to build a 'Constellation Graph' of the user's knowledge.
When answering questions, provide clear and concise explanations. If the question involves multiple steps or complex reasoning, break down your response into manageable parts.

STRICT FORMAT RULES (MANDATORY):
1. You MUST NOT use LaTeX, MathJax, or KaTeX under any circumstance.
2. You MUST NOT use:
   - \\int
   - \\frac
   - subscripts like _{ }
   - superscripts like ^{ }
   - brackets like \\left or \\right
3. You MUST NOT use math symbols such as:
   ∫ ∑ √ ≤ ≥ ≠
4. You MUST write ALL math in plain text ONLY.

ALLOWED math examples:
- x^2
- 3x + 5
- (x + 1)(x - 2)
- sqrt(x)
- a/b

DISALLOWED examples (NEVER use):
- \\int x dx
- \\frac{a}{b}
- x^{2}
- ∫_0^2
- [ x^2 ]_0^2

STYLE RULES:
- Explain step by step.
- Use very simple English (like teaching a 13-year-old).
- No jargon unless explained.
- No fancy formatting.
- No diagrams made with symbols.
- Use normal sentences and numbered steps only.

MONITORING TRIGGERS:
You must analyze every turn of the conversation and use your tools when appropriate.

1. TRIGGERING 'create_knowledge_node':
   - Use this when a brand new topic is introduced, a subtopic is identified, or the user asks to save information.
   - SENIORITY LEVEL RULES: 
     * Level 0 (Root): Broad domains (e.g., 'Science', 'Languages', 'Programming').
     * Level 1 (Major): Significant sub-fields (e.g., 'Biology', 'Spanish', 'Web Development').
     * Level 2 (Atomic): Specific concepts, tasks, or facts (e.g., 'Diffusion', 'Verb Conjugation', 'React Hooks'). 

2. TRIGGERING 'create_knowledge_link':
   - You MUST trigger this tool ANY TIME you realize two nodes are related, or immediately after creating a node that belongs to a parent topic.
   - If a user asks "How does X relate to Y?", answer them AND trigger the link tool.
   - Use 'PARENT_OF' for hierarchical links (e.g., Biology -> Diffusion).
   - Use 'SYNAPSE' for parallel cross-references.

CONTENT FORMATTING RULES:
When you decide a node must be created, you must generate the markdown content using this exact template. Do not deviate:

{{DATE}}
Status: #active
Tags: [[Parent_Topic]] [[Current_Topic]]

{{Topic Name}}

Notes
{{Detailed explanation of the concept, keeping it under 1000 words. Use subheaders.}}

Metadata (Auto-generated by Morgan)
- Familiarity Score: {{0-10 based on user's demonstrated knowledge}}
- Last Updated: {{DATE}}
- Parent Node: [[Parent_Topic]]
- Related Topics: [[Related_1]] [[Related_2]]"

CRITICAL SPEED RULES:
1. Keep conversational responses under 3 sentences.
2. When creating markdown for a node, be EXTREMELY concise. Limit the markdown content to 150 words maximum. Use short bullet points instead of long paragraphs.

TAGGING AND LINKING RULES:
Whenever you write markdown for a node, you must also use '[[tag]]' syntax for connections. This is IN ADDITION to calling the 'create_knowledge_link' tool.
- To make a hierarchical connection (Solid Line), use a tag for a broader topic (e.g., [[Biology]]).
- To make a cross-reference connection (Dotted Line), use tags for related but parallel topics.

SELF-CHECK RULE (VERY IMPORTANT):

Before sending the final answer:
- Check if ANY forbidden symbol or LaTeX-style formatting appears.
- If yes, REWRITE the entire answer using plain text only.

If you break any rule above, the response is considered incorrect and must be rewritten.
`;

const constellationTools = [{
  functionDeclarations: [
    {
      name: "create_knowledge_node",
      description: "Creates a new knowledge node in the user's constellation graph and saves the markdown content.",
      parameters: {
        type: "OBJECT",
        properties: {
          label: {
            type: "STRING",
            description: "The title of the knowledge node."
          },
          seniority_level: {
            type: "INTEGER",
            description: "Hierarchy level: 0 for Root/North Star, 1 for Major topics, 2 for Atomic tasks/concepts."
          },
          cluster_id: {
            type: "STRING",
            description: "The broad category or domain this node belongs to (e.g., 'biology', 'programming')."
          },
          markdown_content: {
            type: "STRING",
            description: "The detailed notes formatted strictly according to the node template."
          }
        },
        required: ["label", "seniority_level", "cluster_id", "markdown_content"]
      }
    },
    {
      name: "create_knowledge_link",
      description: "Creates a relationship link between two existing knowledge nodes based on their labels.",
      parameters: {
        type: "OBJECT",
        properties: {
          source_topic: {
            type: "STRING",
            description: "The exact label of the origin node."
          },
          target_topic: {
            type: "STRING",
            description: "The exact label of the destination node."
          },
          relation_type: {
            type: "STRING",
            description: "The type of relationship: 'PARENT_OF', 'SYNAPSE', 'REQUIRES', or 'BUILDS_ON'."
          }
        },
        required: ["source_topic", "target_topic", "relation_type"]
      }
    }
  ]
}];

async function executeTool(name, args, userId = "FkNqVdJkVXUKTrErRvD204mNI3q2") {
  console.log(`Executing tool: ${name}`, args);

  try {
    if (name === "create_knowledge_node") {
      const existingNodeSnap = await db.collection('users').doc(userId).collection('nodes')
        .where('label', '==', args.label).limit(1).get();
        
      if (!existingNodeSnap.empty) {
        console.log(`Node '${args.label}' already exists. Skipping duplication.`);
        return true; // Pretend we updated the graph so the AI is happy
      }
      // 1. Save the markdown content to 'files' collection
      const fileRef = await db.collection('files').add({
        user_id: userId,
        filename: `${args.label}.md`,
        content: args.markdown_content,
        created_at: FieldValue.serverTimestamp()
      });

      // 2. Save the node to 'nodes' collection with the file_path link
      const newNode = {
        label: args.label,
        seniority_level: args.seniority_level,
        cluster_id: args.cluster_id,
        status: 'ACTIVE',
        file_path: fileRef.id,
        metadata: { familiarity_score: 0, learning_progress: 0, last_updated: new Date().toISOString() },
        created_at: FieldValue.serverTimestamp()
      };
      await db.collection('users').doc(userId).collection('nodes').add(newNode);
      return true; // Indicates the graph was updated
    }

    if (name === "create_knowledge_link") {
      // Look up the actual Document IDs based on the topic labels the AI provided
      const nodesRef = db.collection('users').doc(userId).collection('nodes');
      const sourceSnap = await nodesRef.where('label', '==', args.source_topic).limit(1).get();
      const targetSnap = await nodesRef.where('label', '==', args.target_topic).limit(1).get();

      if (!sourceSnap.empty && !targetSnap.empty) {
        await db.collection('users').doc(userId).collection('links').add({
          source_id: sourceSnap.docs[0].id,
          target_id: targetSnap.docs[0].id,
          relation_type: args.relation_type,
          strength: args.relation_type === 'PARENT_OF' ? 1.0 : 0.1,
          created_at: FieldValue.serverTimestamp()
        });
        return true;
      }
      console.log("Could not find matching nodes to link.");
      return false;
    }
  } catch (error) {
    console.error("Tool execution failed:", error);
    return false;
  }
}

exports.chatGemini = onRequest({
  cors: true, secrets: [GEMINI_API_KEY, DEEPSEEK_API_KEY], 
  timeoutSeconds: 300,
  memory: "1GB"
}, async (req, res) => {
  const {history = [], message} = req.body;
  if (!message) {
    return res.status(400).send("Message is required");
  }

  const ai = new GoogleGenAI({
    apiKey: GEMINI_API_KEY.value(),
  });

  const classificationPrompt = `
  Classify the user message.

  Rules:
  - SIMPLE: casual chat, short answers, basic explanations
  - COMPLEX: coding, math, multi-step reasoning, long analysis

  Reply with ONLY one word:
  SIMPLE or COMPLEX

  User message:
  "${message}"
  `;

  const classificationResult = await ai.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: classificationPrompt,
  });

  const decision = classificationResult.text.trim().toUpperCase();

  let finalText;
  let graphUpdated;

  const today = new Date().toISOString().split('T');
  const dynamicSystemPrompt = SYSTEM_PROMPT + `\n\nCRITICAL RULE: Today's date is ${today}. You MUST use ${today} whenever you fill out the {{DATE}} or {{TIMESTAMP}} fields in your templates.`;

  if (decision == "COMPLEX") {
    try {
      const dsResult = await callDeepSeek(message, history, dynamicSystemPrompt);
      finalText = dsResult.text;
      graphUpdated = dsResult.graphUpdated;
    } catch (error) {
      res.status(200).json({
        model: "System",
        message: error.message || "Error calling DeepSeek API",
      });
      return;
    }
  } else {
    const recentHistory = history.slice(-6);

    const chat = await ai.chats.create({
      model: "gemini-3-flash-preview",
      history: recentHistory.map((m) => ({
        role: m.role, parts: [{text: m.text}],
      })),
    });

    const response = await chat.sendMessage({
      message: message,
      config: {
        systemInstruction: dynamicSystemPrompt,
        tools: constellationTools
      },
    });

    if (response.functionCalls && response.functionCalls.length > 0) {
      for (const call of response.functionCalls) {
        const updated = await executeTool(call.name, call.args);
        
        if (updated) graphUpdated = true;
      }
      
      // AI might not generate text if it calls a tool, so we provide a fallback
      finalText = response.text || "I have mapped this to your knowledge constellation.";
    } else {
      finalText = response.text;
    }
  }

  res.status(200).json({
    model: "Morgan",
    message: finalText,
    graphUpdated: graphUpdated
  });
});

const deepseekTools = [
  {
    type: "function",
    function: {
      name: "create_knowledge_node",
      description: "Creates a new knowledge node in the user's constellation graph and saves the markdown content.",
      parameters: {
        type: "object",
        properties: {
          label: {
            type: "string",
            description: "The title of the knowledge node."
          },
          seniority_level: {
            type: "integer",
            description: "Hierarchy level: 0 for Root/North Star, 1 for Major topics, 2 for Atomic tasks/concepts."
          },
          cluster_id: {
            type: "string",
            description: "The broad category or domain this node belongs to (e.g., 'biology', 'programming')."
          },
          markdown_content: {
            type: "string",
            description: "The detailed notes formatted strictly according to the node template."
          }
        },
        required: ["label", "seniority_level", "cluster_id", "markdown_content"]
      }
    }
  },
  {
    type: "function",
    function: {
      name: "create_knowledge_link",
      description: "Creates a relationship link between two existing knowledge nodes based on their labels.",
      parameters: {
        type: "object",
        properties: {
          source_topic: {
            type: "string",
            description: "The exact label of the origin node."
          },
          target_topic: {
            type: "string",
            description: "The exact label of the destination node."
          },
          relation_type: {
            type: "string",
            description: "The type of relationship: 'PARENT_OF', 'SYNAPSE', 'REQUIRES', or 'BUILDS_ON'."
          }
        },
        required: ["source_topic", "target_topic", "relation_type"]
      }
    }
  }
];

async function callDeepSeek(message, history, dynamicSystemPrompt) {
  const openai = new OpenAI({
    baseURL: "https://api.deepseek.com",
    apiKey: DEEPSEEK_API_KEY.value(),
  });

  const recentHistory = history.slice(-6);

  const completion = await openai.chat.completions.create({
    model: "deepseek-chat",
    messages: [
      {
        role: "system",
        content: dynamicSystemPrompt,
      },
      ...recentHistory.map((m) => ({
        role: normalizeRole(m.role),
        content: m.text,
      })),
      {
        role: "user",
        content: message,
      },
    ],
    tools: deepseekTools
  });

  const choice = completion.choices[0];
  let finalText = "";
  let graphUpdated = false;

  // --- DEEPSEEK INTERCEPTION LOGIC ---
  if (choice.message.tool_calls && choice.message.tool_calls.length > 0) {
    for (const call of choice.message.tool_calls) {
      const args = JSON.parse(call.function.arguments); 
      const updated = await executeTool(call.function.name, args);
      
      // If any tool succeeds, mark the graph as updated
      if (updated) graphUpdated = true; 
    }
    finalText = choice.message.content || "I've added that to your constellation graph.";
  } else {
    finalText = choice.message.content;
  }

  return { text: finalText, graphUpdated };
}

function normalizeRole(role) {
  if (role === "model" || role === "ai" || role === "assistant") {
    return "assistant";
  }
  if (role === "human" || role === "user") {
    return "user";
  }
  if (role === "system") {
    return "system";
  }
  return "user"; // fallback
}
